apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline4-pvc
  namespace: abc-bank
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pipeline4-pv        # <--- add this line
